### ISSUE TITLE
Oops, an error happened!

### ISSUE THREAD

**Issue by Belanchuk** [deficient/volume-control#1]
I getting error:
(sciping)/volume-control.lua:36: attempt to call local 'arg' (a nil value)

**Comment by coldfix** [comment]
Strange. The `arg` function is defined right above the same way the `argv` function is defined as well (where the error occurs). So it's confusing that the one function can be called from within the script and the other can't.

Maybe you have some other script that overwrites `arg` globally? But even then the error description doesn't seem to fit.

What version of lua are you running?

You could try to rename `arg`. Specifically, change `arg` to `make_argument` or similar in lines 27, 31 and 36.

If this doesn't work, replace line 36 by 

```
return table.concat({...}, " ")
```

which should be fine for the scope of this script.

**Comment by Belanchuk** [comment]
I replace arg by arg_vol, the error does not appear.
But I can not see mixer and key binding do not work.

I do not have "Master" channel:
/home/user % amixer -c 0 | pcregrep "control"
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958',1
Simple mixer control 'IEC958',2

But, when I replace:
volumecfg = volume_control({channel="Master"})
by:
volumecfg = volume_control({channel="IEC958"})
nothing changes.

**Comment by coldfix** [comment]
Try

``` lua
volumecfg = volume_control({cardid=0,channel="IEC958"})
```

Do the terminal commands

``` bash
amixer -c 0 set IEC958 50%
amixer -c 0 set IEC958 100%
```

change the volume as expected?

**Comment by Belanchuk** [comment]
This is worked:
volumecfg = volume_control({cardid=1,channel="Master"})
Thanks! )

**Comment by coldfix** [comment]
Great.

By the way, I believe (cmiiw!) that you do not need to (and shouldn't) specify any arguments to the control if you have pulseaudio properly installed.

**Comment by Belanchuk** [comment]
May be. How can I check it?

**Comment by coldfix** [comment]
- install pulseaudio.
- reboot.
- modify the code to `volumecfg = volume_control()`

**Comment by coldfix** [comment]
Correction: the last line should read `volumecfg = volume_control({})`

**Comment by Belanchuk** [comment]
I have install pulseaudio and reboot but this is do not work: volumecfg = volume_control({})

**Comment by agisga** [comment]
I ran into the same problem as @Belanchuk on Awesome WM installed on top of Ubuntu Gnome 16.04.
I just want to let you know my solution in case anybody stumbles upon the same problem.

The correct amixer commands to change the volume in my case are of the form:

```
amixer -D pulse set Master 5%+
amixer -D pulse set Master 5%-
etc
```

In order to make the volume widget work I changed [line 109](https://github.com/coldfix/awesome.volume-control/blob/master/volume-control.lua#L109) to
```
command = argv(self.cmd, "-D", self.device, ...)
```
(where I also replaced `cardid` with `device` throughout), and I defined the volume control in rc.lua as
```
volumecfg = volume_control({device="pulse", channel="Master"})
```

Everything works great now! Thanks for this awesome script!

**Comment by coldfix** [comment]
Great, thanks! Can you create a pull-request with your changes (might be useful for others).

**Comment by coldfix** [comment]
@agisga Nevermind, I have implemented it on master. Thanks for pointing it out again.

**Comment by agisga** [comment]
Nice! Thanks! (Yours is definitely a much better implementation than mine since I actually don't know lua)
