### ISSUE TITLE
Pango markup in widget_text

### ISSUE THREAD

**Issue by bhartshorn** [deficient/volume-control#12]
Tried to use Pango markup in the widget format, which just prints the markup without parsing it.
```
local volumecfg = volume_control({
    widget_text = {
        on  = " <span color='red'>V</span>: % 3d%% |",        -- three digits, fill with leading spaces
        off = " <span color='red'>V</span>: % 3dM |",
    },
})
```
This is simply due to using `set_text()` instead of `set_markup()`. Could be a feature, rather than a bug? Seems like many users would want to use markup though.

**Comment by coldfix** [comment]
Honestly, I don't know whether I just never needed it or if there were any problems due to `set_markup`. Anyway, I changed it to `set_markup` now.
