### ISSUE TITLE
Volume % displayed in widget differs from alsamixer

### ISSUE THREAD

**Issue by tzar** [deficient/volume-control#13]
`amixer` by default reports volume % based on raw values whereas `alsamixer` by default reports volume % based on "mapped volume". This means that the volume % displayed in the widget and in alsamixer is usually not the same and it looks like the step value you configure to use in the widget is ignored (even though it's not). It's relatively easy to switch `amixer` to also use mapped volume so the two agree:

```
diff --git a/volume-control.lua b/volume-control.lua
index 386b8af..9c7027d 100644
--- a/volume-control.lua
+++ b/volume-control.lua
@@ -122,6 +122,7 @@ end
 function vcontrol:mixercommand(...)
     local args = awful.util.table.join(
       {self.cmd},
+      (self.cmd == "amixer") and {"-M"} or {},
       self.device and {"-D", self.device} or {},
       self.cardid and {"-c", self.cardid} or {},
       {...})
```

**Comment by coldfix** [comment]
Sure enough thanks for the suggestion!
