### ISSUE TITLE
Add Text before Percentage

### ISSUE THREAD

**Issue by Mag1cByt3s** [deficient/volume-control#14]
Is there a way to add a text before the percentage of the widget? Like Vol: 36% , something like that?
Otherwise i always have to figure out what widget it is

**Comment by coldfix** [comment]
Sure, create the widget with:

```lua
widget = volume_control {
  widget_text = {
    on  = 'Vol % 3d%% ',        -- three digits, fill with leading spaces
    off = 'Vol % 3dM ',
  },
}
```

**Comment by Mag1cByt3s** [comment]
Thx it works
