### ISSUE TITLE
crash during startup with multiple monitors

### ISSUE THREAD

**Issue by CodeFarmer** [deficient/volume-control#15]
This one comes with a couple of symptoms.

Going from one monitor to two with xrandr, the the task bar does not appear on the second monitor:

![2020-06-28_12-47](https://user-images.githubusercontent.com/129549/85946647-b344de00-b93d-11ea-8ce5-5fe1696c71a3.png)

Restarting awesome (more helpful):

![2020-06-28_12-41](https://user-images.githubusercontent.com/129549/85946667-d1aad980-b93d-11ea-98d2-aa90d268fe87.png)

In the second case, I also see doubled task bars on the primary monitor, and the secondary now has one working taskbar and one blank one:

![2020-06-28_12-42](https://user-images.githubusercontent.com/129549/85946677-e7200380-b93d-11ea-87ae-5dea1c1b0cb1.png)

**Comment by CodeFarmer** [comment]
This is on Sparky Linux rolling release, so I can't give you a precise OS version number. But:

- awesome 4.3-4 amd64
- awesome-extra 2019021001 all

**Comment by coldfix** [comment]
The error message indicates that there might be something wrong with how the `self` argument was passed. My best guess is that `widget.method()` was used somewhere instead of `widget:method()` (method call vs attribute access). Please provide your config code related to volume control.

**Comment by CodeFarmer** [comment]
(TL;DR: Can reproduce with a single monitor and Xephyr, the problem is in the object's response to drill().)

Hi... after you closed this one I stopped using multiple monitors for a while. However I tried it again a week ago and have a bit more understanding of what is going on (although my Lua is almost nonexistent). My config is set up exactly as instructed in the README, so I'm hopeful this will be meaningful.

The problem is in the common rc.lua section that starts

`awful.screen.connect_for_each_screen(function(s)`

and continues

```
s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            mylauncher,
            s.mytaglist,
            s.mypromptbox,
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            mykeyboardlayout,
            wibox.widget.systray(),
	    volumecfg,
            s.mylayoutbox,
        },
    }
```

When there is only one screen, this is fine. However, when there are multiple screens, setup() gets called on the same instance ('volumecfg') multiple times. This in turn means that 'drill()' in widget/base.lua also gets called multiple times, and that does a bunch of reflective activity that appears to be trying to call all the exposed methods.

(I found it helpful to demonstrate this myself by using Xephyr and putting volumecfg twice in the widget list, to avoid having to use multiple screens. But the effect and symptoms are identical).

As I said, my Lua is rudimentary, but the object returned be `volume_control({})` seems to do some fancy one-time setup that is unlike other widget objects that seem to cope with being repeatedly set up. Something about the object does not expect to be run through drill() multiple times, and it ends up perhaps exposing `show_menu()` during the first run, (which then gets reflectively called during the second run) before `create_menu()` is available to it?

**Comment by CodeFarmer** [comment]
For what it's worth, your battery-widget copes with this fine!

**Comment by coldfix** [comment]
Hey, thanks for the additional info. I'll investigate later.

**Comment by coldfix** [comment]
Hi,

reading through your description, I noticed that you seem to add the `volumecfg` object returned from `volumecfg = volume_control({})` directly to the list of widgets. However, you have to use its `volumecfg.widget` attribute, not the object itself. Does this clear out the problem, or did you already do this? (Although it would be weird that this behaves differently depending on how many monitors are plugged in with otherwise the same config..)

Best, Thomas

**Comment by CodeFarmer** [comment]
Light dawns :)

That definitely resolves it. It turns out that

> My config is set up exactly as instructed in the README

is total nonsense though, for which I can only apologise. It's been that way since December 2017, so I can't even remember where I got the idea that it was the right thing to do... something to do with the magic of drill() was making the volume control work as designed though, despite my misconfiguration. Which is kind of impressive now that I think of it.

Thank you for your patience and your help!

**Comment by coldfix** [comment]
Great! No problem;)
