### ISSUE TITLE
After the switch mute can not turn on the sound

### ISSUE THREAD

**Issue by Belanchuk** [deficient/volume-control#2]
After the switch mute can not turn on the sound.
![mute](https://cloud.githubusercontent.com/assets/159318/14088564/be4c9c82-f549-11e5-8bba-975d40c82173.png)

**Comment by coldfix** [comment]
Oh, I'm sorry for the trouble. I forgot that I also needed the `pulseaudio-alsa` package (archlinux) to make it work properly. In case you are running another distribution, the package configures ALSA to use pulseaudio and contains the following file at `/etc/asound.conf`:

``` conf
# Use PulseAudio by default
pcm.!default {
  type pulse
  fallback "sysdefault"
  hint {
    show on
    description "Default ALSA Output (currently PulseAudio Sound Server)"
  }
}

ctl.!default {
  type pulse
  fallback "sysdefault"
}
```

I guess you probably need to reboot again after adding the file. The reason I mentioned pulseaudio is that in my experience it simplified a lot of audio-related tasks like controlling the volume.

**Comment by Belanchuk** [comment]
No, this code in /etc/asound.conf noesn't work.

**Comment by coldfix** [comment]
I have to admit that I'm no expert for linux audio either. If you can't make it work using the instructions on the [archwiki](https://wiki.archlinux.org/index.php/PulseAudio#Back-end_configuration) (delete `~/.asoundrc`?), I recommend to switch back to the previous configuration that worked:)

(By the way, rather than changing the lua code I recommend to use the amixer command to quickly test what configuration and which card/channel works.)

**Comment by Belanchuk** [comment]
ok )

**Comment by Belanchuk** [comment]
This is work from console:
amixer -D pulse set Master 1+ toggle

**Comment by Belanchuk** [comment]
In rc.lua I change:
awful.key({}, "XF86AudioMute",function  () volumecfg:toggle() end),
to:
awful.key({}, "XF86AudioMute",function () awful.util.spawn("amixer -D pulse set Master 1+ toggle") end),

Thank! )

**Comment by coldfix** [comment]
Okay, looks like alsa is indeed not properly configured to use pulseaudio, not sure why the configuration in `asound.conf` doesn't work. If you want to use your hotfix, better change the toggle command in `volume-control.lua`, line 108 to:

``` lua
    self:update(self:mixercommand("set", "-D", "pulse", self.channel, "toggle"))
```

**Comment by Belanchuk** [comment]
Ok, thk!
