### ISSUE TITLE
Oops, there were errors during startup!

### ISSUE THREAD

**Issue by Ahg4goo9** [deficient/volume-control#3]
I set up volume control to use cardid 0 and pulse:
```
volumecfg = volume_control({
    device = "pulse",
    cardid = 0
})
```
It works fine in a terminal:
`amixer -D pulse -c 0 set Master 5%-` works.
But for some reasons awesome complains on startup. I probably configure the widget in a wrong way, but I am not able to figure out in which ;-).
```
2017-03-05` 16:41:19 E: Error during a protected call: /home/liffi/.config/awesome/volume-control.lua:36: attempt to call local 'arg' (a nil value)
stack traceback:
        /home/liffi/.config/awesome/volume-control.lua:36: in function 'argv'
        /home/liffi/.config/awesome/volume-control.lua:111: in function 'mixercommand'
        /home/liffi/.config/awesome/volume-control.lua:116: in function 'get'
        /home/liffi/.config/awesome/volume-control.lua:68: in function 'func'
        /usr/share/awesome/lib/gears/object.lua:116: in function </usr/share/awesome/lib/gears/object.lua:113>
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:30: in function </usr/share/awesome/lib/gears/protected_call.lua:28>
        (tail call): ?
        /usr/share/awesome/lib/gears/timer.lua:49: in function </usr/share/awesome/lib/gears/timer.lua:48>
```

**Comment by coldfix** [comment]
Hey,

thanks for your report!

Strange, you're the second person to report this, see #1. You can use the suggested fix from there.

Just out of curiosity, can you play around with this a bit?

- which version of lua/awesome are you running?
- Do you have any other variables called `arg` in the rest of your code?
- Does it work if you change the name of the `arg` function
- does it help to declare it as `local arg; arg = function (first, ...) `
- does it help to make it global?

**Comment by coldfix** [comment]
Also, how do you use the volume control, do you use `require`?

**Comment by Ahg4goo9** [comment]
> which version of lua/awesome are you running?

awesome v4.0 Compiled against Lua 5.1.5 (running with Lua 5.1)

> Do you have any other variables called arg in the rest of your code?

Not that I know of. At least not in rc.lua which is basically the default rc.lua from Debian.

> Does it work if you change the name of the arg function

It indeed does. So it seems it is declared twice.

> does it help to declare it as local arg; arg = function (first, ...)
> does it help to make it global?

Nope. Both won't work.

EDIT::

> Also, how do you use the volume control, do you use require?

Yes, I use `local volume_control = require("volume-control")`

**Comment by coldfix** [comment]
Thanks. I guess I'll just rename it. Maybe it is some naming conflict with the global `arg` which holds the command line.

Can you try one more thing though: go back to the original code and add `local table = table; local string = string` to the top of the file. Does it help? (I am just reading that sometimes lua raises incorrect error messages...)

**Comment by Ahg4goo9** [comment]
> Can you try one more thing though: go back to the original code and add local table = table; local string = string to the top of the file. Does it help?

That did not help.

Thanks for the widget btw. When I rename arg, it works like a charm :-).

**Comment by coldfix** [comment]
Thanks. I now renamed the function upstream as well. Still not sure what's causing this issue...
