### ISSUE TITLE
ALSA

### ISSUE THREAD

**Issue by cassiel74** [deficient/volume-control#5]
How can this be done for ALSA? I use jackd...

**Comment by coldfix** [comment]
> How can this be done for ALSA?

How can what be done?

The control uses amixer, i.e. ALSA, currently, so once you figure out, how to use the amixer command utility, it should be trivial to adjust the widget (all it takes might be adding a `device` argument, but I have no clue about jackd).

**Comment by cassiel74** [comment]
I managed to make it work with my old keybindings.
Sorry for the garbage
