### ISSUE TITLE
Selecting default sink doesn't work

### ISSUE THREAD

**Issue by ptpj** [deficient/volume-control#6]
When selecting a sink, its index is being passed to vcontrol:set_default_sink, which then calls  `pactl set-default-sink <index>`. The call fails with 'Failure: No such entity'. According to pactl manpage, the name of the sink is expected by the command.

A possible fix could look something like this: 

```lua
-- Get the name of the n-th audio sink listed by pactl
function vcontrol:get_nth_sink(i)
  local names = readcommand("pactl list sinks"):gmatch("Name: ([^\n]+)")
  for j = 1, i do names() end
  return names()
end

function vcontrol:set_default_sink(i)
  os.execute(("pactl set-default-sink %s"):format(self:get_nth_sink(i)))
end
```

**Comment by coldfix** [comment]
Hm, this works on my machine. Might be due to version mismatch? I'm running 

```
% pactl --version
pactl 11.1
Compiled with libpulse 11.1.0
Linked with libpulse 11.1.0
```

What's yours?

Best, Thomas

**Comment by ptpj** [comment]
Could be, mine is 4.0

**Comment by coldfix** [comment]
Hi, I pushed a version that should be compatible with `pactl` versions that don't understand the ID as argument. Let me know, if you still have problems.

Best, and thanks for reporting, Thomas

**Comment by denisoster** [comment]
Hi, Thomas. My problem. 
![image](https://user-images.githubusercontent.com/15886355/34537055-ddb44cfe-f0cf-11e7-87b6-103227bcab13.png)

`$ pactl --version`
`pactl 11.1`
`Скомпилировано с libpulse 11.1.0`
`Скомпоновано с libpulse 11.1.0`

  [log](https://gist.github.com/denisoster/f96d1daa8bb20f35c5f888df473fc3b0)

**Comment by coldfix** [comment]
Hi, can you show the output of `pactl list sinks`?

**Comment by coldfix** [comment]
@denisoster I suspect this is caused by your locale. You can try again on the most recent version, see 3b1be7151f43af6c97d54023675ac8a1a67a7bc2. If this doesn't work, can you try play around with adding locale related parameters to

```
env LC_ALL=.. pactl list sinks
```

until you see english output?

Best, Thomas

**Comment by denisoster** [comment]
@coldfix Thanks)
